// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpuQxJuv__OfzPjjhq7i-3QjtzGoBHf0Q',
    appId: '1:121245023955:web:f65a18cbeb5c72e7a59e26',
    messagingSenderId: '121245023955',
    projectId: 'school-bus-e9a0a',
    authDomain: 'school-bus-e9a0a.firebaseapp.com',
    storageBucket: 'school-bus-e9a0a.firebasestorage.app',
    measurementId: 'G-EVE8S9XVR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8N4m8LHdXOwCDKLkYnFbplIAUA6zEyM',
    appId: '1:121245023955:android:5681faf20ff69808a59e26',
    messagingSenderId: '121245023955',
    projectId: 'school-bus-e9a0a',
    storageBucket: 'school-bus-e9a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoupeDkZ7bBV8yfKDB4aRG0Fo7TkLIaFI',
    appId: '1:121245023955:ios:8eb6e5eea32f02bea59e26',
    messagingSenderId: '121245023955',
    projectId: 'school-bus-e9a0a',
    storageBucket: 'school-bus-e9a0a.firebasestorage.app',
    iosBundleId: 'com.example.schoolBusPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoupeDkZ7bBV8yfKDB4aRG0Fo7TkLIaFI',
    appId: '1:121245023955:ios:8eb6e5eea32f02bea59e26',
    messagingSenderId: '121245023955',
    projectId: 'school-bus-e9a0a',
    storageBucket: 'school-bus-e9a0a.firebasestorage.app',
    iosBundleId: 'com.example.schoolBusPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpuQxJuv__OfzPjjhq7i-3QjtzGoBHf0Q',
    appId: '1:121245023955:web:bb84c8bfbb0e784ba59e26',
    messagingSenderId: '121245023955',
    projectId: 'school-bus-e9a0a',
    authDomain: 'school-bus-e9a0a.firebaseapp.com',
    storageBucket: 'school-bus-e9a0a.firebasestorage.app',
    measurementId: 'G-TTMRQV0W92',
  );
}
